#! /bin/sh

source ~/.zshenv

#AUTOSTART
mate-polkit &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
pgrep picom && killall picom
picom -bCG
$HOME/.config/polybar/launch.sh &
variety &
xsetroot -cursor_name left_ptr &
flameshot &
xinput --set-prop "Logitech USB-PS/2 Optical Mouse" "libinput Accel Speed" -0.45
setxkbmap -option caps:escape
kdeconnect-indicator &
$HOME/.local/bin/nextcloud-client &
#$HOME/.scripts/disk-standby &
$HOME/.scripts/week/monday.sh &
$HOME/.scripts/week/tuesday.sh &
$HOME/.scripts/week/wednesday.sh &
$HOME/.scripts/week/thursday.sh &
$HOME/.scripts/week/friday.sh &

#MONITORS
xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x420 --rotate normal --output HDMI-0 --primary --mode 1920x1080 --pos 1920x420 --rotate normal --output DP-0 --off --output DP-1 --off --output DVI-D-1 --mode 1920x1080 --pos 3840x0 --rotate left

bspc monitor DVI-D-0 -d 💬 2 3
=======
[ "$(cat /etc/hostname)" = "pop-os" ] && xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x420 --rotate normal --output HDMI-0 --primary --mode 1920x1080 --pos 1920x420 --rotate normal --output DP-0 --off --output DP-1 --off --output DVI-D-1 --mode 1920x1080 --pos 3840x0 --rotate left
[ "$(cat /etc/hostname)" = "asus" ] && xrandr --output e-DP-1-1 --mode 1366x768
bspc monitor DVI-D-0 -d 💬 2 3 
bspc monitor HDMI-0 -d 4 5 6 🎮
#bspc monitor DVI-D-0 -s HDMI-0
bspc monitor DVI-D-1 -d 8 9 0

[ "$(cat /etc/hostname)" = "asus" ] && bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 0

#BSPWM SETTINGS
bspc config focused_border_color "#e78a4e"
bspc config normal_border_color "#282828"
bspc config urgen_border_color "#ea6962"
bspc config active_border_color "#89b482"

bspc config border_width         5
bspc config window_gap         	10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

[ "$(cat /etc/hostname)" = "pop-os" ] && bspc desktop -f 4

#RULES
bspc rule -r *
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a BashTOP state=floating
bspc rule -a Variety state=floating
bspc rule -a flameshot state=floating
bspc rule -a Yad state=floating
bspc rule -a feh state=fullscreen
bspc rule -a Eddy state=floating
bspc rule -a Wine desktop=^7 follow=on
bspc rule -a csgo_linux64 desktop=^7 follow=on
bspc rule -a Steam dekstop=^6 follow=on
bspc rule -a xonotic-linux64-sdl desktop=^7 state=fullscreen follow=on
bspc rule -a xonotic-linux64-glx desktop=^7 state=fullscreen follow=on
bspc rule -a xpad state=floating layer=below locked=on
bspc rule -a gnome-calculator state=floating
bspc rule -a Signal desktop=^1 follow=on
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Totem state=floating rectangle=600x800
bspc rule -a Toolkit state=floating
bspc rule -a Gnome-calendar state=pseudo_tiled
bspc rule -a Gnome-todo state=pseudo_tiled
bspc rule -a Gnome-font-viewer state=pseudo_tiled
bspc rule -a Bitwarden state=pseudo_tiled
bspc rule -a Bijiben state=pseudo_tiled
bspc rule -a File-roller state=floating
bspc rule -a QOwnNotes stat=floating

#SCRIPTS
~/.scripts/bspwm/cleanfullscreen

steamlib=$HOME/.steam/steam    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^7 state=fullscreen follow=on
done
