#! /bin/sh

#AUTOSTART
mate-polkit &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
$HOME/.config/polybar/launch.sh &
variety &
xsetroot -cursor_name left_ptr &
flameshot &
xinput --set-prop "Logitech USB-PS/2 Optical Mouse" "libinput Accel Speed" -0.45
setxkbmap -option caps:escape

pulseaudio -k
pulseuudio --start

#MONITORS
xrandr --output "DVI-D-1" --auto --output "HDMI-0" --auto --primary --right-of "DVI-D-1"
bspc monitor HDMI-0 -d 1 2 3 4 5 6 🎮
bspc monitor DVI-D-1 -d 8 9 0
bspc monitor DVI-D-1 -s HDMI-0

#BSPWM SETTINGS
bspc config focused_border_color "#e78a4e"
bspc config normal_border_color "#282828"
bspc config urgen_border_color "#ea6962"
bspc config active_border_color "#89b482"

bspc config border_width         5
bspc config window_gap         	10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#RULES
bspc rule -r *
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a BashTOP state=floating
bspc rule -a Variety state=floating
bspc rule -a flameshot state=floating
bspc rule -a Yad state=floating
bspc rule -a feh state=fullscreen
bspc rule -a Eddy state=floating
bspc rule -a Wine desktop=^7 follow=on
bspc rule -a csgo_linux64 desktop=^7 follow=on
bspc rule -a Steam dekstop=^7 state=floating follow=on 
bspc rule -a xonotic-linux64-sdl desktop=^7 state=fullscreen follow=on
bspc rule -a xonotic-linux64-glx desktop=^7 state=fullscreen follow=on

steamlib=$HOME/.steam/steam    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^7 state=fullscreen follow=on 
done
