#!/bin/bash

 #if [ "$HOST" = "pop-os" ]
 #then
     #~/.scripts/bible
 #else
     #pfetch
 #fi
 case $(hostname) in
    pop-os)
        pfetch
    ;;
    pi)
        clear
        ~/.scripts/bible
    ;;
    jerusalem)
        echo hello
    ;;
esac
