#!/bin/sh
choice=$(echo "Polybar
sxhkd
bspwm" | rofi -dmenu -p "Reload" -i)
case $choice in
	Polybar)
		$HOME/.config/polybar/launch.sh
 		notify-send -t 4000 "Polybar reloaded"
	;;
	sxhkd)
		killall sxhkd
		sxhkd &
 		notify-send -t 4000 "Hotkeys reloaded"
	;;
	bspwm)
		bspc wm -r
	;;
esac


